### PR TITLE
Not having a layout file causes a file not found

### PR DESCRIPTION
**Pull request by tedkulp**
I'm using express-partials for the partials, not the layout functionality. Not having a layout template causes an error, so this pull request checks to make sure it still exists and if not, falls back cleanly.

### CODE REVIEW

**Comment by slaskis** [comment]
Looks great! But could you make the tests pass by using `var exists = path.existsSync || fs.existsSync` ?

**Comment by tedkulp** [comment]
Yup, no problem. I saw that Travis failed, but didn't get a chance to go back and look. I'll try and do that before the weekend.

**Comment by tedkulp** [comment]
There we go. Sorry for the delay.

**Comment by slaskis** [comment]
Thanks!

**Pull request merged**
