### PR TITLE
Fixed layout path resolution to be relative to template. Fixes #11.

### LINKED ISSUE #11: Layout Lookup Fails for Subdirectory Templates
Example:

``` javascript
var express = require('express'),
partials = require('express-partials')
app = express();

app.use(partials());

app.set('views', __dirname + "/views");
app.get('/', function(req, res, next) { return res.render('web/homepage.html'); });
```

This will successfully render the template, but will fail on looking up `layout.html` located in the same folder:

```
Error: Failed to lookup view "layout.html"
    at Function.render (/Users/jakub/Documents/apiary/node_modules/express/lib/application.js:493:17)
    at ServerResponse.partial (/Users/jakub/Documents/apiary/node_modules/express/lib/response.js:677:7)
    at /Users/jakub/Documents/apiary/node_modules/express-partials/index.js:63:11
    at /Users/jakub/Documents/apiary/node_modules/consolidate/lib/consolidate.js:182:7
    at /Users/jakub/Documents/apiary/node_modules/consolidate/lib/consolidate.js:65:5
    at [object Object].<anonymous> (fs.js:123:5)
    at [object Object].emit (events.js:64:17)
    at Object.oncomplete (fs.js:1188:12)
```

### PR DESCRIPTION
**Pull request by zzen**
This fixes #11. I'm happy to add tests and try fixing #9, but need help finding out current template.

### CODE REVIEW

**Comment by zzen** [comment]
Oops, no, wait - I think I got the original express behavior wrong. Give me a second to fix the tests and implementation.

**Comment by zzen** [comment]
Nope - looks good, just added one more test to be sure.

**Comment by slaskis** [comment]
Looks good to me, thanks!

**Comment by slaskis** [comment]
Published as 0.0.6 on npm now.

**Comment by zzen** [comment]
Sadly, over the weekend I discovered many more differences between `express 2.x` and `express-partials`. I'll try to consolidate this into another pull-request, but I'm getting convinced that the best way would be to take original `express 2.x` code and just include it.

**Comment by slaskis** [comment]
Well, at least we have two more cases tested for now. If you have time to get more in that'd be fantastic.

**Comment by slaskis** [comment]
Migrating some of [these](https://github.com/visionmedia/express/blob/2.x/test/view.test.js) might be a good start for us?

**Pull request merged**
