### PR TITLE
Fix partial include of a view in a subfolder #2

### PR DESCRIPTION
**Pull request by ecdeveloper**
FIxing partial include of a view within a folder, such as:
<%- partial('user/profile') %>

Till now got the same error as described here - http://stackoverflow.com/questions/12525145/ejs-partials-with-express-in-sub-directory

### CODE REVIEW

**Comment by slaskis** [comment]
This looks about right, thanks!

**Comment by ecdeveloper** [comment]
Waiting for npm repo to be updated with the new version :)

**Comment by slaskis** [comment]
Sorry, I was about to but wanted to add a test for it first. And then I got sidetracked by work. I'll see if I can get it up today. 

You're more than welcome to provide a test if you want to get it up faster ;)

**Comment by ecdeveloper** [comment]
It's not so urgent :) Just wanted to remind you ;)

**Comment by ecdeveloper** [comment]
Still waiting for an updated version of module in npm :)

**Comment by risseraka** [comment]
Up on this.
Any fresh news?

**Comment by slaskis** [comment]
@risseraka well a new version has been published (last week) if that's what you mean?

**Comment by risseraka** [comment]
@slaskis indeed, my bad, we had `express-partials: 0.0.x` in our package.json.
Cheers!

**Pull request merged**
